# Generated by Django 3.2.7 on 2022-02-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, to='dd.UserBadge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='participations',
            field=models.ManyToManyField(blank=True, to='dd.UserParticipation'),
        ),
    ]
